#!/bin/bash

brew install --cask azure-data-studio
brew install --cask brave-browser
brew install --cask companion
brew install --cask cursor
brew install --cask devtoys
brew install --cask devutils
brew install --cask docker
brew install --cask discord
brew install --cask disk-inventory-x
brew install --cask font-fira-code
brew install --cask google-chrome
brew install --cask imageoptim
brew install --cask insomnia
brew install --cask iterm2
brew install --cask joplin
brew install --cask jellyfin-media-player
brew install --cask maccy
brew install --cask mqtt-explorer
brew install --cask nordvpn
brew install --cask notion-calendar
brew install --cask postman
brew install --cask pritunl
brew install --cask rectangle
brew install --cask rescuetime
brew install --cask screenflow
brew install --cask signal
brew install --cask slack
brew install --cask sublime-text
brew install --cask tableplus
brew install --cask tidal
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask whatsapp
brew install --cask zwift
